quality: [95, 95]  # 提高图像质量范围，确保高质量输出

landscape: 0.5
short_size: [720, 1024]
aspect_ratio: [1, 2]

background:
  image:
    paths: [resources/coco/train2017]
    weights: [1]

  effect:
    args:
      # gaussian blur 已禁用
      - prob: 0.0
        args:
          sigma: [0, 10]

document:
  fullscreen: 0.0
  landscape: 0.5
  short_size: [240, 480]
  aspect_ratio: [1, 2]

  paper:
    image:
      paths: [resources/paper]
      weights: [1]
      alpha: [0, 0.1]
      grayscale: 1
      crop: 1

  content:
    margin: [0, 0.1]
    text:
      path: resources/corpus/zhwiki.txt
    font:
      paths: [resources/font/zh]
      weights: [1]
      bold: 0
    layout:
      text_scale: [0.0334, 0.1]
      max_row: 10
      max_col: 3
      fill: [0.5, 1]
      full: 0.3
      align: [left, right, center]
      stack_spacing: [0.0334, 0.0334]
      stack_fill: [0.5, 1]
      stack_full: 0.1
    textbox:
      fill: [0.5, 1]
    textbox_color:
      prob: 0.2
      args:
        gray: [0, 64]
        colorize: 1
    content_color:
      prob: 0.2
      args:
        gray: [0, 64]
        colorize: 1
  text_count:
    min: 30 # 最少生成的文字数量
    max: 60 # 最多生成的文字数量

  effect:
    args:
      # elastic distortion 概率降低
      - prob: 0.1
        args:
          alpha: [0, 1]
          sigma: [0, 0.5]
      # gaussian noise 概率降低
      - prob: 0.1
        args:
          scale: [0, 8]
          per_channel: 0
      # perspective 概率降低
      - prob: 0.1
        args:
          weights: [750, 50, 50, 25, 25, 25, 25, 50]
          args:
            - percents: [[0.75, 1], [0.75, 1], [0.75, 1], [0.75, 1]]
            - percents: [[0.75, 1], [1, 1], [0.75, 1], [1, 1]]
            - percents: [[1, 1], [0.75, 1], [1, 1], [0.75, 1]]
            - percents: [[0.75, 1], [1, 1], [1, 1], [1, 1]]
            - percents: [[1, 1], [0.75, 1], [1, 1], [1, 1]]
            - percents: [[1, 1], [1, 1], [0.75, 1], [1, 1]]
            - percents: [[1, 1], [1, 1], [1, 1], [0.75, 1]]
            - percents: [[1, 1], [1, 1], [1, 1], [1, 1]]

text_effect:
  args:
    # rotate 已禁用
    - prob: 0.0
      args:
        angle: [-3, 3]
    # elastic distortion 已禁用
    - prob: 0.0
      args:
        alpha: [0, 0.8]
        sigma: [0, 0.3]
    # gaussian blur 已禁用
    - prob: 0.0
      args:
        sigma: [0, 1.0]

shape:
  prob: 0.0  # 形状变形已禁用
  args:
    weights: [1, 1]
    args:
      # elastic distortion
      - alpha: [15, 30]
        sigma: [4, 12]
      # elastic distortion
      - alpha: [0, 2]
        sigma: [0, 0.6]

effect:
  args:
    # color
    - prob: 0.2
      args:
        rgb: [[0, 255], [0, 255], [0, 255]]
        alpha: [0, 0.2]
    # shadow
    - prob: 0.1
      args:
        intensity: [0, 160]
        amount: [0, 1]
        smoothing: [0.5, 1]
        bidirectional: 0
    # 移除了 contrast, brightness, motion blur 和 gaussian blur 的配置

